# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: 'refine-ticket/refine-sorted-template'

prompts:
  - file://prompts/*.yml

providers:
  - file://../../providers.yml

tests:
  - vars:
      sorted_template: file://vars/sorted_template/feature_*.json
      schema: file://vars/schema/schema-feature.json
    assert:
    - type: contains-json
      value: file://vars/schema/schema-feature.json
    - type: llm-rubric
      value: "Provides a faithful refinement of the user's content that's better in style and has less errors without adding ungrounded details or removing important ones. User's content: \n{{sorted_template}}\n\nprovided schema:\n{{schema}}"
      provider: file://../../default_judge.yml